### PR TITLE
move AfterSave method from relay to storage

### PR DESCRIPTION
**Pull request by qustavo**
AfterSave has been moved to `storage`

### CODE REVIEW

**Comment by barkyq** [comment]
If you remove these, then the `AdvancedSaver` hooks in `add-event.go` won't be triggered. Both `BeforeSave` and `AfterSave`need to be implemented in order for the relay to implement `AdvancedSaver` interface.

Perhaps this was your intention. Just checking in case you did not know about the hooks...

**Comment by qustavo** [comment]
I see what you mean, and I think you are partially right, but `AdvancedSaver` is now taken from the `storage`: https://github.com/fiatjaf/relayer/blob/c7d584da5495dc15633a89e2607b6024dcc8d610/add-event.go#L11-L12

So I think instead of removing the methods, they should be moved to the storage.

**Comment by barkyq** [comment]
Ah yes you are right... the AdvancedSaver interface should be implemented by the "storage", not by the relay. Strange though that the basic and expensive examples define BeforeSave and AfterSave methods for the relay itself. What do you think?

**Comment by barkyq** [comment]
looks good, should we also add a BeforeSave() method which does nothing to the postgresql code?

**Comment by qustavo** [comment]
I think it's a left over from some refactor.
I moved `AfterSave` to the storage and remove it from the binaries

**Comment by barkyq** [comment]
and by "we" I mean "you", since you are doing all the work here :)

**Comment by qustavo** [comment]
We definitively need to, otherwise it won't satisfy the interface.

**Comment by barkyq** [comment]
Looks good to me! Nice catch. We'll see if Fiatjaf likes it :+1:

**Comment by qustavo** [comment]
Also, reviewing this made me think that `{Before,After}Save` could also return an error.

**Comment by barkyq** [comment]
Agreed on ability to return error. seems like more "idiomatic" go to return errors. Fiatjaf maybe will allow you to change the signature of the interface, but maybe not :man_shrugging:

**Comment by fiatjaf** [comment]
Can you explain to me why this is better than the current state? I'm not following.

**Comment by qustavo** [comment]
> AdvancedSaver is now taken from the storage: https://github.com/fiatjaf/relayer/blob/c7d584da5495dc15633a89e2607b6024dcc8d610/add-event.go#L11-L12

**Comment by fiatjaf** [comment]
But why? I'm just trying to understand.

**Comment by fiatjaf** [comment]
Oh, this PR is not moving stuff to `Storage`, they are already there because I moved them? Sorry for the stupid questions in this case and thank you for this PR.

**Pull request merged**
