### PR TITLE
Terraform IaC module and Ansible role to deploy `relayer` in GCP

### PR DESCRIPTION
**Pull request by nir3shprabu**

### CODE REVIEW

**Comment by nir3shprabu** [comment]
No relayer in production is deployed using this infra stack, however, AFAIK, it is well tested and will work as intended.

This PR will see some incoming commits in the following week, which will improve the security of the instances, the introduction of a task runner for the `tf` commands, and the overall structure of the project in general.

I'll switch the status of this PR to a _Draft_ for the stated reasons.

I have plans to add support for many other cloud providers in the pipeline, i.e; AWS, Linode, Vultr, Hetzner

**Comment by fiatjaf** [comment]
Why are you going to do that if you don't intend to run it?

Relayer is a library, not a finished product, I think these automation things will work better on nostr-rs-relay, strfry, nostr-relay.untethr.me, nostrex and nostream, which are production-ready finished relay software products.

**Comment by nir3shprabu** [comment]
> Why are you going to do that if you don't intend to run it?

Oh, I most definitely do plan to use this to run relayer in production, indeed yes.

> Relayer is a library, not a finished product

It isn't now, but sure would be in the not-so-distant future, maybe a year from now? Relayer has been and will remain to be the first relay implementation in Go.

I believe my contribution to be a natural next step in streamlining the way relay runners stand-up their relays without having to worry about all the security bells and whistles (IAM and such) that any modern Cloud provider offers, that, and also leveraging ansible to harden the OS once the infra is provisioned, makes it all the more beneficial for the relay ecosystem by and large.

> I think these automation things will work better on nostr-rs-relay, strfry, nostr-relay.untethr.me, nostrex and nostream, which are production-ready finished relay software products.

You are right on that, they just might benefit from this.

**Comment by nir3shprabu** [comment]
- Introduced a `Makefile` to abstract away the manual labor of running the terraform commands themselves
- Dropped a `terraform.tfvars.example` file and added a target inside `Makefile` generating a placeholder with all the variable inputs which the user can then fill in
- Now fetching the docker role from ansible galaxy, as opposed to GitHub.
 
All in all, I approve of the changes that went into this PR and will signal to merge it in.

**Comment by fiatjaf** [comment]
Even though I don't understand what is happening here I feel like this is a very specific GCP terraform stuff with no practical use cases for anyone, and you're not even using it yourself (which is puzzling to me). Before merging I would like to see some evidence that is this is a good idea.

**Comment by fiatjaf** [comment]
Sorry, I didn't mean to discredit your work. I don't know what is the best approach to handle this.

**Pull request closed without merging**
